# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='标记为默认'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='标记为删除'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
