# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171027_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章'},
        ),
    ]
