# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20171027_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='封面'),
        ),
    ]
