# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='文章内容'),
        ),
    ]
