# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20171028_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=False, verbose_name='审核通过'),
        ),
    ]
