# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='go_index',
            field=models.BooleanField(default=False, verbose_name='推荐到首页'),
        ),
    ]
