# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20171103_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='封面')),
            ],
        ),
    ]
