# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '文章'},
        ),
    ]
