# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20171103_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name_plural': '文章'},
        ),
    ]
